theme: jeykyll-theme-minimal
title: The Mordell conjecture 100 years later
description: This celebration of a century of mathematics inspired by Mordell's conjecture will take place July 8-12, 2024 at the Massachusetts Institute of Technology
